name: pdf_commande_app
description: "Une application Flutter pour générer des PDF de commandes"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.1
  pdf: ^3.10.0
  image_picker: ^1.0.4
  share_plus: ^7.2.1
  printing: ^5.11.0
  intl: ^0.18.1
  permission_handler: ^11.0.1
  archive: ^3.3.6
  shared_preferences: ^2.2.2
  universal_html: ^2.2.1
  file_picker: ^10.2.1
  image: ^4.1.4
  path: ^1.8.3
  url_launcher: ^6.1.11
  flutter_image_compress: ^2.0.0
  http: ^1.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/commande_icon.png
    - assets/data/default_catalogue.json